### ISSUE TITLE
Table notes parse error

### ISSUE THREAD

**Issue by DigitalFeonix** [softwaretechnik-berlin/dbml-renderer#15]
Cannot use double quotes for a Table Note, the renderer throws a parse error while it works fine in [dbdiagram.io](https://dbdiagram.io/d)

test.dbml

```
Table Bids {
    BidKey int [pk]
    Inactive bool [default: false]
    CreateDate timestamp
    LastUpdated timestamp

    Note: "a vendor's bid for a job"
}
```

```shell
C:\dev\open-source\dbml-tests>dbml-renderer -i test.dbml -o test.svg
Could not parse input at line 7. Expected "'", "\\\"", [\\], or [^"\\] but "\"" found.
```

**Comment by barnardb** [comment]
Yes, this is expected behaviour. In DBML, double-quotes are used to escape identifiers. Strings can be quoted with `'` or `'''`. See e.g. [Table Notes](https://www.dbml.org/docs/#table-notes), [Multi-line String](https://www.dbml.org/docs/#multi-line-string) and [Syntax Consistency](https://www.dbml.org/docs/#syntax-consistency) in the DBML docs.
